/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as CustomerRouteImport } from './routes/_customer'
import { Route as MerchantIndexRouteImport } from './routes/merchant/index'
import { Route as CustomerIndexRouteImport } from './routes/_customer/index'
import { Route as MerchantSettingsRouteImport } from './routes/merchant/settings'
import { Route as MerchantReviewsRouteImport } from './routes/merchant/reviews'
import { Route as MerchantOrdersRouteImport } from './routes/merchant/orders'
import { Route as MerchantMenuRouteImport } from './routes/merchant/menu'
import { Route as MerchantKdsRouteImport } from './routes/merchant/kds'
import { Route as MerchantEmployeesRouteImport } from './routes/merchant/employees'
import { Route as CustomerProfileRouteImport } from './routes/_customer/profile'
import { Route as CustomerOrdersRouteImport } from './routes/_customer/orders'
import { Route as CustomerExploreRouteImport } from './routes/_customer/explore'
import { Route as CustomerCartRouteImport } from './routes/_customer/cart'
import { Route as CustomerPaymentReturnRouteImport } from './routes/_customer/payment.return'
import { Route as CustomerMenuItemIdRouteImport } from './routes/_customer/menu.$itemId'
import { Route as CustomerMenuItemIdRouteImport } from './routes/_customer/menu.$itemId'

const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/_customer',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const MerchantSettingsRoute = MerchantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantReviewsRoute = MerchantReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantMenuRoute = MerchantMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantKdsRoute = MerchantKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantEmployeesRoute = MerchantEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => MerchantRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerExploreRoute = CustomerExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerPaymentReturnRoute = CustomerPaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerMenuItemIdRoute = CustomerMenuItemIdRouteImport.update({
  id: '/menu/$itemId',
  path: '/menu/$itemId',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerMenuItemIdRoute = CustomerMenuItemIdRouteImport.update({
  id: '/menu/$itemId',
  path: '/menu/$itemId',
  getParentRoute: () => CustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof CustomerIndexRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/cart': typeof CustomerCartRoute
  '/explore': typeof CustomerExploreRoute
  '/orders': typeof CustomerOrdersRoute
  '/profile': typeof CustomerProfileRoute
  '/merchant/employees': typeof MerchantEmployeesRoute
  '/merchant/kds': typeof MerchantKdsRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/reviews': typeof MerchantReviewsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/merchant/': typeof MerchantIndexRoute
  '/menu/$itemId': typeof CustomerMenuItemIdRoute
  '/payment/return': typeof CustomerPaymentReturnRoute
}
export interface FileRoutesByTo {
  '/cart': typeof CustomerCartRoute
  '/explore': typeof CustomerExploreRoute
  '/orders': typeof CustomerOrdersRoute
  '/profile': typeof CustomerProfileRoute
  '/merchant/employees': typeof MerchantEmployeesRoute
  '/merchant/kds': typeof MerchantKdsRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/reviews': typeof MerchantReviewsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/': typeof CustomerIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/menu/$itemId': typeof CustomerMenuItemIdRoute
  '/payment/return': typeof CustomerPaymentReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_customer': typeof CustomerRouteWithChildren
  '/merchant': typeof MerchantRouteWithChildren
  '/_customer/cart': typeof CustomerCartRoute
  '/_customer/explore': typeof CustomerExploreRoute
  '/_customer/orders': typeof CustomerOrdersRoute
  '/_customer/profile': typeof CustomerProfileRoute
  '/merchant/employees': typeof MerchantEmployeesRoute
  '/merchant/kds': typeof MerchantKdsRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/reviews': typeof MerchantReviewsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/_customer/': typeof CustomerIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/_customer/menu/$itemId': typeof CustomerMenuItemIdRoute
  '/_customer/payment/return': typeof CustomerPaymentReturnRoute
  '/_customer/menu/$itemId': typeof CustomerMenuItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/merchant'
    | '/cart'
    | '/explore'
    | '/orders'
    | '/profile'
    | '/merchant/employees'
    | '/merchant/kds'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/merchant/reviews'
    | '/merchant/settings'
    | '/merchant/'
    | '/menu/$itemId'
    | '/payment/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cart'
    | '/explore'
    | '/orders'
    | '/profile'
    | '/merchant/employees'
    | '/merchant/kds'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/merchant/reviews'
    | '/merchant/settings'
    | '/'
    | '/merchant'
    | '/menu/$itemId'
    | '/payment/return'
  id:
    | '__root__'
    | '/_customer'
    | '/merchant'
    | '/_customer/cart'
    | '/_customer/explore'
    | '/_customer/orders'
    | '/_customer/profile'
    | '/merchant/employees'
    | '/merchant/kds'
    | '/merchant/menu'
    | '/merchant/orders'
    | '/merchant/reviews'
    | '/merchant/settings'
    | '/_customer/'
    | '/merchant/'
    | '/_customer/menu/$itemId'
    | '/_customer/payment/return'
    | '/_customer/menu/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CustomerRoute: typeof CustomerRouteWithChildren
  MerchantRoute: typeof MerchantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer': {
      id: '/_customer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/_customer/': {
      id: '/_customer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/merchant/settings': {
      id: '/merchant/settings'
      path: '/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof MerchantSettingsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/reviews': {
      id: '/merchant/reviews'
      path: '/reviews'
      fullPath: '/merchant/reviews'
      preLoaderRoute: typeof MerchantReviewsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/menu': {
      id: '/merchant/menu'
      path: '/menu'
      fullPath: '/merchant/menu'
      preLoaderRoute: typeof MerchantMenuRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/kds': {
      id: '/merchant/kds'
      path: '/kds'
      fullPath: '/merchant/kds'
      preLoaderRoute: typeof MerchantKdsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/employees': {
      id: '/merchant/employees'
      path: '/employees'
      fullPath: '/merchant/employees'
      preLoaderRoute: typeof MerchantEmployeesRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/_customer/profile': {
      id: '/_customer/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/orders': {
      id: '/_customer/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/explore': {
      id: '/_customer/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof CustomerExploreRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/cart': {
      id: '/_customer/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/payment/return': {
      id: '/_customer/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof CustomerPaymentReturnRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/menu/$itemId': {
      id: '/_customer/menu/$itemId'
      path: '/menu/$itemId'
      fullPath: '/menu/$itemId'
      preLoaderRoute: typeof CustomerMenuItemIdRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerExploreRoute: typeof CustomerExploreRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerMenuItemIdRoute: typeof CustomerMenuItemIdRoute
  CustomerPaymentReturnRoute: typeof CustomerPaymentReturnRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerCartRoute: CustomerCartRoute,
  CustomerExploreRoute: CustomerExploreRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerMenuItemIdRoute: CustomerMenuItemIdRoute,
  CustomerPaymentReturnRoute: CustomerPaymentReturnRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface MerchantRouteChildren {
  MerchantEmployeesRoute: typeof MerchantEmployeesRoute
  MerchantKdsRoute: typeof MerchantKdsRoute
  MerchantMenuRoute: typeof MerchantMenuRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantReviewsRoute: typeof MerchantReviewsRoute
  MerchantSettingsRoute: typeof MerchantSettingsRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantEmployeesRoute: MerchantEmployeesRoute,
  MerchantKdsRoute: MerchantKdsRoute,
  MerchantMenuRoute: MerchantMenuRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantReviewsRoute: MerchantReviewsRoute,
  MerchantSettingsRoute: MerchantSettingsRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CustomerRoute: CustomerRouteWithChildren,
  MerchantRoute: MerchantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
